### PR TITLE
create data directory when doesn't exist , use get method insteand of view , delete unused file , create a single editor template 

### PR DESCRIPTION
**Pull request by ngdream**
create data directory when doesn't exist , use get method insteand of view , delete unused file , create a single editor template

### CODE REVIEW

**Comment by HanslettTheDev** [comment]
Great Idea! But I think the implementation still needs work. If we are creating one route for the editor, The template itself has to reflect changes based on the button clicked. for example, if I clicked the open button, the redirected page should contain information pertaining to the open section. As you said, we need to implement something that can scale with the application. And this is a desktop application, not a web app. so it needs to behave almost like one though it's not native. Check the [TODO.md](https://github.com/osscameroon/TypePen/blob/main/TODO.md) on the list of things required to better this project. Your solution will work currently but over time, it might cause conflicts. Any suggestion to improve this will be greatly appreciated

**Comment by Sanix-Darker** [comment]
Hey @ngdream , thank yu for the contribution!
This is why, before contributing on an open source project, it's great to open first an issue and exchange on how the code is going to go before opening a pull request related to the issue !
I think it's okay for now, since this Pull Request doesn't require too much changes, but in the future, it will have been better to start with an issue (if you didn't have the discussion with maintainer in another canal or the Pull Request is about something really tiny)!

---

And also, please try to follow this template when you're opening a pull request : 

## WHAT
>> explain what the Pull request is all about with list of checkboxes(no need to write the Bible, be precise on what you're trying todo)
Checkboxes are going to tell us if there is some work still ongoing or not
- [ ] task one blablabla
- [x] task three blablabla
- [ ] ... need to discuss again, blabla blabla

## HOW
>> Explain how you achieved it

## SCREENSHOTS
>> Provide screenshots if there are needed (like on this PR, since you changed the UI)

**Comment by ngdream** [comment]
> Great Idea! But I think the implementation still needs work. If we are creating one route for the editor, The template itself has to reflect changes based on the button clicked. for example, if I clicked the open button, the redirected page should contain information pertaining to the open section. As you said, we need to implement something that can scale with the application. And this is a desktop application, not a web app. so it needs to behave almost like one though it's not native. Check the [TODO.md](https://github.com/osscameroon/TypePen/blob/main/TODO.md) on the list of things required to better this project. Your solution will work currently but over time, it might cause conflicts. Any suggestion to improve this will be greatly appreciated


there will be no conflicts, and concerning the open or save functions, all must be managed by the javascript

**Comment by HanslettTheDev** [comment]
These pull requests won't be merged because after testing the code, not every function was working. for example, the path to the files wasn't working, when you open the file, the text formatting should be kept including the text; this means the html should be rendered once the page opens.

*POSITIVES*
Nice adjustment with the JS functions
Hover effect on the text box
reduced redundancy with code

We need a solid design foundation to base the idea so it's more structured rather than just bits of adjustment on files that can change subsequently

**Comment by ngdream** [comment]
i did modification to correct  bugs

**Comment by ngdream** [comment]
please can you say me which function doesn't works ???

**Pull request closed without merging**
